---

domain: ec2-52-90-175-222.compute-1.amazonaws.com                       
domain_www: ec2-52-90-175-222.compute-1.amazonaws.com                
resolver: 8.8.8.8
nginx_worker_processes: "{{ ansible_processor_cores }}"
