---

php_repo: "ppa:ondrej/php"
php_packages:
  - php7.2-fpm
  - php7.2-common
  - php7.2-cli
  - php7.2-intl
  - php7.2-curl
  - php7.2-mysql
  - php7.2-gd
  - php7.2-mbstring
  - php7.2-mcrypt
  - php7.2-memcached
  - php7.2-apcu
  - php7.2-xml
  - php7.2-json
